version: "3.7"

services:

  dispatcher:
    build: .
    command: python /dispatcher.py
    network_mode: host

  calculator:
    build: .
    command: python /calculator.py
    network_mode: host
    depends_on:
      - dispatcher

  client:
    build: .
    command: python /client.py
    network_mode: host
    depends_on:
      - dispatcher